services:
  hfs-charges-nightly-process:
    image: hfs-charges-nightly-process
    build:
      context: .
      dockerfile: ./HfsChargesContainer/Dockerfile
    env_file:
       - .env
    network_mode: host
