version: 2.1

orbs:
  aws_assume_role: lbh-hackit/aws_assume_role@0.1.0
  aws-cli: circleci/aws-cli@0.1.9

executors:
  docker-python:
    docker:
      - image: circleci/python:3.7
  docker-dotnet:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0-alpine
  cci-aws:
    docker:
      - image: cimg/aws:2023.08

references:
  workspace_root: &workspace_root "~"
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

commands:
  assume-role-and-persist-workspace:
    description: "Assumes deployment role and persists credentials across jobs"
    parameters:
      aws-account:
        type: string
    steps:
      - checkout
      - aws_assume_role/assume_role:
          account: <<parameters.aws-account>>
          profile_name: default
          role: "LBH_Circle_CI_Deployment_Role"
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .aws
  deploy-image:
    description: "Deploys application image to ECR"
    parameters:
      environment:
        type: string
        description: environment stage
    steps:
      - *attach_workspace
      - checkout
      - setup_remote_docker
      - run:
          name: Build the application image
          command: |
            ENVIRONMENT=<<parameters.environment>>
            CHARGES_ECR_NAME_SSM_KEY="/hfs/nightly/${ENVIRONMENT}/charges-ingest/ecr-name"
            ECR_NAME=$(aws ssm get-parameter --name ${CHARGES_ECR_NAME_SSM_KEY} --region "eu-west-2" --query Parameter.Value --output text)

            docker build -t ${ECR_NAME} HfsChargesContainer
      - run:
          name: Tag and Deploy to ECR
          command: |
            ENVIRONMENT=<<parameters.environment>>
            CHARGES_ECR_URL_SSM_KEY="/housing/${ENVIRONMENT}/ecr-url"
            CHARGES_ECR_NAME_SSM_KEY="/hfs/nightly/${ENVIRONMENT}/charges-ingest/ecr-name"

            ECR_URL=$(aws ssm get-parameter --name ${CHARGES_ECR_URL_SSM_KEY} --region "eu-west-2" --query Parameter.Value --output text)
            ECR_NAME=$(aws ssm get-parameter --name ${CHARGES_ECR_NAME_SSM_KEY} --region "eu-west-2" --query Parameter.Value --output text)

            aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin ${ECR_URL}

            docker tag ${ECR_NAME}:latest ${ECR_URL}/${ECR_NAME}:latest
            docker push ${ECR_URL}/${ECR_NAME}:latest

jobs:
  check-code-formatting:
    executor: docker-dotnet
    steps:
      - checkout
      - run:
          name: Install dotnet format
          command: dotnet tool install dotnet-format --tool-path ./dotnet-format-local/
      - run:
          name: Run formatter check
          command: ./dotnet-format-local/dotnet-format --check
  run-automated-tests:
    executor: docker-python
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Prepare the test container for build
          command: |
            # docker-compose expects to see this file even though it's not asked to spin up the main app container
            cp .env.sample .env
      - run:
          name: Running automated tests
          command: docker-compose run hfs-charges-nightly-process-tests
  assume-role-development:
    executor: docker-python
    steps:
      - assume-role-and-persist-workspace:
          aws-account: $AWS_ACCOUNT_DEVELOPMENT
  assume-role-staging:
    executor: docker-python
    steps:
      - assume-role-and-persist-workspace:
          aws-account: $AWS_ACCOUNT_STAGING
  assume-role-production:
    executor: docker-python
    steps:
      - assume-role-and-persist-workspace:
          aws-account: $AWS_ACCOUNT_PRODUCTION
  deploy-to-development:
    executor: cci-aws
    steps:
      - deploy-image:
          environment: "development"
  deploy-to-staging:
    executor: docker-dotnet
    steps:
      - deploy-image:
          environment: "staging"
  deploy-to-production:
    executor: docker-dotnet
    steps:
      - deploy-image:
          environment: "production"

workflows:
  check-and-deploy-development:
    jobs:
      - check-code-formatting:
          filters:
            branches:
              ignore: release
      - run-automated-tests:
          requires:
            - check-code-formatting
          filters:
            branches:
              ignore: release
      - permit-deployment:
          type: approval
          requires:
            - run-automated-tests
          filters:
            branches:
              only: dummy-connection-timeout-test
      - assume-role-development:
          context: api-assume-role-housing-development-context
          requires:
              - permit-deployment
          filters:
            branches:
              only: dummy-connection-timeout-test
      - deploy-to-development:
          requires:
              - assume-role-development
          filters:
            branches:
              only: dummy-connection-timeout-test
